{% set name = "qfit" %}
{% set version = "3.0.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qfit-{{ version }}.tar.gz
  sha256: 0db495bb19da74e6b4f4a049025ac5b1b98a1185b2a14dcedc4edecd707a64e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - wheel
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.14.2
    - matplotlib-base >=3.1.2
    - pyside6
    - h5py >=2.7.1
    - scikit-image
    - scqubits >=3.0.0
    - matplotlib-label-lines
    - ipykernel
    - jupyter
    - pathos
    - dill
    # scqubits' conda build profile (meta.yaml) is different from the pip 
    # installation profile (pyproject.toml), so we need to add extra packages to 
    # make sure it passes the pip check. The additional requirements introduce
    # inconsistencies between the qfit's pyproject.toml and meta.yaml, too.
    # - scipy >=1.5,<1.13.1
    - cython >=0.29.20

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - qfit
  commands:
    - pip check

about:
  home: https://github.com/scqubits/qfit
  summary: 'qfit: data extraction GUI tool for use with scQubits'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Harrinive
    - ZhaoTianPu
